stages:
  - build
  - deploy

.stg-vars:
  variables:
    ENVIRONMENT: stg
    IMAGE_URL: ${DOCKER_REGISTRY}/aic22-frontend:stg
    SWARM_MASTER_NODE: ${STG_SWARM_MASTER_NODE}
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

.production-vars:
  variables:
    ENVIRONMENT: production
    IMAGE_URL: ${DOCKER_REGISTRY}/aic22-frontend:${CI_COMMIT_SHORT_SHA}
    SWARM_MASTER_NODE: ${PRD_SWARM_MASTER_NODE}
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

.build:
  stage: build
  image: ${DOCKER_REGISTRY}/docker:19.03.12
  tags:
    - docker
  script:
    - docker build . -t ${IMAGE_URL}
    - docker push ${IMAGE_URL}

.deploy:
  stage: deploy
  before_script:
    - chmod -R 700 $SSH_PRIVATE_KEY
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ${SWARM_MASTER_NODE} -t "docker pull ${IMAGE_URL}"
  script:
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ${SWARM_MASTER_NODE} -t "docker service update --image ${IMAGE_URL} aic_frontend_${ENVIRONMENT}"

stg-build:
  extends:
    - .stg-vars
    - .build

production-build:
  extends:
    - .production-vars
    - .build

stg-deploy:
  extends:
    - .stg-vars
    - .deploy

production-deploy:
  extends:
    - .production-vars
    - .deploy